<a href="https://colab.research.google.com/github/lalitapunmagar1/AI-ML/blob/main/introduction/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to NumPy

What we will cover


*   Creating Single Dimensional Arrays

*   Multidimensional array

*   Randomly generated array
*   Element wise operation


*   Summarizing operation




###Single dimensional arrays

In [2]:
#create an array with all the elements to be zeros
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
#creating an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
#creating an array of size 10 with all elements 3
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###Multidimensional arrays

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a[0,1]=20
a

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [27]:
a[2]=[1,1,1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
a[:, 2]= [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [33]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

###Randomly generated arrays





*   NumPy can create arrays filled with random numbers
*   To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions


*   If you emove or change the seed valuse, the sequence of random numbers will be changed







In [34]:
np.random.rand(5)

array([0.90504396, 0.81830273, 0.24228528, 0.80158486, 0.5326451 ])

In [36]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [38]:
np.random.randn(5,2)

array([[ 0.54794733, -0.52658091],
       [ 1.17223107, -0.48103231],
       [-1.00073842, -1.18248113],
       [-0.43654296, -2.64063134],
       [ 0.01571955,  0.02997534]])

In [39]:
np.random.randint(low=0, high=100, size=(5,2))

array([[24,  1],
       [17, 54],
       [16, 41],
       [20, 31],
       [24, 67]])